services:
  - type: web
    name: color-accessibility-checker
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
